exec = hyprctl setcursor Bibata-Modern-Classic 28

# Set wallpaper
exec = swaybg -i $hypr/wallpaper.png

# Plugins and stuff
exec = hyprpm enable split-monitor-workspaces

exec-once = hypridle

# Authentication agent
exec-once = /usr/lib/polkit-kde-authentication-agent-1

# Utilities
exec = killall notification-daemon; $notificationDaemon
# exec-once = sleep 8; eww daemon && sleep 1; eww open bar1 && eww open bar2
exec-once = waybar
exec-once = walker --gapplication-service -c $HOME/.config/eww/config.json
exec-once = flameshot
exec-once = nm-applet
exec-once = megasync

# Programs
exec-once = [monitor eDP-1] $terminal dooit
exec-once = [monitor HDMI-A-1] thunderbird
