exec = hyprctl setcursor Bibata-Modern-Classic 28

# Set wallpaper
exec = swaybg -i $hypr/wallpaper.png

# Plugins and stuff
exec = hyprpm enable split-monitor-workspaces

exec-once = hypridle

# Authentication agent
exec-once = /usr/lib/polkit-kde-authentication-agent-1

# Utilities
exec = killall notification-daemon; $notificationDaemon
exec-once = sleep 8; eww daemon && sleep 1; eww open bar1 && eww open bar2
exec-once = walker --gapplication-service
exec-once = flameshot
exec-once = nm-applet

# Programs
# exec-once = obsidian
# exec-once = [workspace 1] brave
# exec-once = sleep 8; brave --app="http://notion.so"
# exec-once = sleep 8; brave --app="http://calendar.notion.so"
exec-once = $terminal nvim +':ObsidianToday'
