$terminal           = kitty

$notificationDaemon = fnott
$menu               = walker -m applications

$editor             = kitty nvim
$fileManager        = kitty yazi
$browser            = zen-browser
$systemMonitor      = kitty btop
$musicPlayer        = kitty cmus
