$terminal           = kitty

$notificationDaemon = fnott
$menu               = walker --theme=simple

$editor             = kitty nvim
$fileManager        = kitty yazi
$browser            = zen-browser
$systemMonitor      = kitty btop
$musicPlayer        = kitty cmus
