$terminal           = kitty

$notificationDaemon = fnott
$menu               = walker -m applications

$fileManager        = kitty yazi
$browser            = brave --ozone-platform=wayland
$systemMonitor      = kitty btop
$musicPlayer        = kitty cmus
