# Example windowrule v1
# windowrule = float, ^(kitty)$

# Example windowrule v2
# windowrulev2 = float,class:^(kitty)$,title:^(kitty)$

windowrulev2 = suppressevent maximize, class:.* # You'll probably like this.

# Better looking animation for flameshot
windowrule = animation popin 100%, ^(flameshot)$

# Notification animations
windowrule = animation slide right, ^(Walker)$

# Floating
# windowrulev2 = float, class:(brave-browser), initialTitle:^(Untitled - Brave)$ #Pop-Ups?
windowrule = float, ^(flameshot)$
windowrule = float, ^(xdg-desktop-portal-gtk)$
windowrule = float, ^(pavucontrol-qt)$
windowrule = float, ^(pavucontrol)$
