# Example windowrule v1
# windowrule = float, ^(kitty)$

# Example windowrule v2
# windowrulev2 = float,class:^(kitty)$,title:^(kitty)$

windowrulev2 = suppressevent maximize, class:.* # You'll probably like this.

# Better looking animation for flameshot
windowrule = animation popin 100%, ^(flameshot)$

# Floating
windowrule = float, ^(flameshot)$
windowrule = float, ^(xdg-desktop-portal-gtk)$
windowrule = float, ^(pavucontrol-qt)$
windowrule = float, ^(pavucontrol)$
windowrule = float, ^(ls-tasks)$
windowrule = float, ^(python3)$
windowrule = float, ^(MEGAsync)$
windowrule = float, ^(pomatez)$
windowrulev2 = float, class:^(anki)$, title:^(Add)$
windowrulev2 = float, class:^(anki)$, title:^(Browse.*)$

# Tiled (Some programs start floating for some reason...)
windowrule = tile, ^(Aseprite)$

# Pinned
windowrule = pin, ^(pomatez)$

# Sizes
windowrule = size 70% 60%, ^(ls-tasks)$

# Positioning
# windowrule = move 100%-580 70, ^(MEGAsync)$
windowrule = move cursor -50% 40, ^(MEGAsync)$

# Workspaces
windowrule = workspace special:notion, ^(brave-notion.so__-Default)$
windowrule = workspace special:calendar, ^(brave-calendar.notion.so__-Default)$

# No idle
windowrule = idleinhibit, ^(dolphin-emu)$

# Some rules have to be handled with scripts...
exec-once = $hypr/scripts/popup_rules
