# Example windowrule v1
# windowrule = float, ^(kitty)$

# Example windowrule v2
# windowrulev2 = float,class:^(kitty)$,title:^(kitty)$

windowrulev2 = suppressevent maximize, class:.* # You'll probably like this.

# Better looking animation for flameshot
windowrule = animation popin 100%, ^(flameshot)$

# Floating
windowrule = float, ^(flameshot)$
windowrule = float, ^(xdg-desktop-portal-gtk)$
windowrule = float, ^(pavucontrol-qt)$
windowrule = float, ^(pavucontrol)$

# Workspaces
windowrule = workspace special:calendar, ^(brave-calendar.notion.so__-Default)$

# Some rules have to be handled with scripts...
exec-once = $hypr/scripts/popup_rules
