#!/usr/bin/env sh

socat -U - UNIX-CONNECT:$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock | while read -r line; do
    case $line in
    'activewindow>>'*)
        title=$(echo "$line" | awk -F'brave-browser,' '{print $2}')
        echo $title

        case "$title" in
        'Inicia sesión: Cuentas de Google - Brave')
            echo YES
            hyprctl dispatch setfloating title:"$title"
            hyprctl dispatch centerwindow
            ;;
        esac

        ;;
    esac
done
