set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'christoomey/vim-tmux-navigator'
# set -g @plugin 'janoamaral/tokyo-night-tmux'
# set -g @plugin 'fabioluciano/tmux-tokyo-night'

SCRIPTS_PATH="~/.config/tmux/scripts"

# set -g default-terminal 'screen-256color'
# set -g default-terminal 'xterm-256color'
set-option -ga terminal-overrides ',xterm-256color:Tc'

setw -g automatic-rename on
set -g monitor-activity on
set -g visual-activity off

# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

################
## STATUS BAR ##
################

set -g status-position top

# set -g @theme_variation night
# set -g @theme_left_separator ''
# set -g @theme_right_separator ''
#
# set -g @theme_plugin_datetime_icon '  '
# set -g @theme_plugin_datetime_format ' %I:%M %P '
#
# set -g @theme_transparent_status_bar 'true'
# set -g @theme_transparent_left_separator_inverse ''
# set -g @theme_transparent_right_separator_inverse ''

# set -g status-left "#[fg=#3b4261,bold]#{?client_prefix,#[bg=#e0af68],#[bg=#9ece6a]}  #S #[bg=#292e42]#{?client_prefix,#[fg=#e0af68],#[fg=#9ece6a]}#[none]"
# set -g status-right "#[fg=#3d59a1,bg=#292e42]#[none]#[fg=#ffffff,bg=#3d59a1]  #[fg=#394b70,bg=#3d59a1]#[none]#[fg=#ffffff,bg=#394b70] %I:%M %P #[none]"

set -g status-style bg=default,fg=#A9B1D6

set -g status-left-length 100

set @col-bg "#222436"

set @col-active "#7AA2F7"

set @col-bg-inactive "#15161E"
set @col-bg-active "#1E2234"
set @col-fg-inactive "#222436"
set @col-fg-active "#A9B1D6"

set @bar-prefix-indicator "#{?client-prefix,#[bg=#9ece6a]#[fg=#1A1B26],#[bg=#{@col-bg-inactive},fg=#{@col-fg-inactive}]}  "
set @bar-session "#[bg=#BB9AF7,fg=#1A1B26]  #[bg=#{@col-bg},fg=default] #S "

set -g status-left "#[bold]#{E:@bar-session}#[default]#{E:@bar-prefix-indicator}#[default]  "

set @col-window-icon-active "#0DD3BB"
set @col-window-icon-inactive "#222436"
set @window-icon " "
set @window-id "#($SCRIPTS_PATH/custom_number.sh #I fsquare)"

set -g window-status-format "#[bg=#{@col-bg-inactive}]  #[fg=#{@col-window-icon-inactive}]#{@window-icon}#[fg=#{@col-fg-inactive}]#{@window-id} #W  "
set -g window-status-current-format "#[bg=#{@col-bg-active}]  #[fg=#{@col-window-icon-active}]#{@window-icon}#[fg=#{@col-fg-active}]#{@window-id} #W  "
set -g window-status-separator ''

##############
## BINDINGS ##
##############

# Navigate windows with Alt+H/L
bind -n M-H previous-window
bind -n M-L next-window

# Create window
bind -n C-n neww

## PREFIX KEYS ##

bind C-x kill-window
bind X kill-session

# Splits
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# Create a session
bind n new

# Pane resizing
bind -r H resize-pane -L 2
bind -r J resize-pane -D 2
bind -r K resize-pane -U 2
bind -r L resize-pane -R 2

# Swap panes
bind -r C-l swap-pane -D
bind -r C-h swap-pane -U

# Better yanking
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

run '~/.tmux/plugins/tpm/tpm'
