set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'christoomey/vim-tmux-navigator'
# set -g @plugin 'janoamaral/tokyo-night-tmux'
set -g @plugin 'fabioluciano/tmux-tokyo-night'

# set -g default-terminal 'screen-256color'
# set -g default-terminal 'xterm-256color'
set-option -ga terminal-overrides ',xterm-256color:Tc'

setw -g automatic-rename on
set -g monitor-activity on
set -g visual-activity off

# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

################
## STATUS BAR ##
################

set -g status-position top

set -g @theme_variation night
set -g @theme_left_separator ''
set -g @theme_right_separator ''

set -g @theme_plugin_datetime_icon '  '
set -g @theme_plugin_datetime_format ' %I:%M %P '

set -g @theme_transparent_status_bar 'true'
set -g @theme_transparent_left_separator_inverse ''
set -g @theme_transparent_right_separator_inverse ''

##############
## BINDINGS ##
##############

# Navigate windows with Alt+H/L
bind -n M-H previous-window
bind -n M-L next-window

# Create window
bind -n C-n neww

## PREFIX KEYS ##

bind C-x kill-window
bind X kill-session

# Splits
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# Create a session
bind n new

# Pane resizing
bind -r H resize-pane -L 2
bind -r J resize-pane -D 2
bind -r K resize-pane -U 2
bind -r L resize-pane -R 2

# Swap panes
bind -r C-l swap-pane -D
bind -r C-h swap-pane -U

# Better yanking
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

run '~/.tmux/plugins/tpm/tpm'
