#! /bin/env bash

workspaces() {
    if [[ $1 -eq 0 ]]; then
        # Primary monitor
        w1=1
        w2=2
        w3=3
        w4=4
        w5=5
        w6=6
        w7=7
        w8=8
        w9=9
        w10=10
    elif [[ $1 -eq 1 ]]; then
        # Secondary monitor
        w1=11
        w2=12
        w3=13
        w4=14
        w5=15
        w6=16
        w7=17
        w8=18
        w9=19
        w10=20
    fi

    # w1=1
    # w2=2
    # w3=3
    # w4=4
    # w5=5
    # w6=6
    # w7=7
    # w8=8
    # w9=9
    # w10=10

    declare -A o

    o[$w1]=$(hyprctl workspaces -j | grep "\"id\": ${w1},")
    o[$w2]=$(hyprctl workspaces -j | grep "\"id\": ${w2},")
    o[$w3]=$(hyprctl workspaces -j | grep "\"id\": ${w3},")
    o[$w4]=$(hyprctl workspaces -j | grep "\"id\": ${w4},")
    o[$w5]=$(hyprctl workspaces -j | grep "\"id\": ${w5},")
    o[$w6]=$(hyprctl workspaces -j | grep "\"id\": ${w6},")
    o[$w7]=$(hyprctl workspaces -j | grep "\"id\": ${w7},")
    o[$w8]=$(hyprctl workspaces -j | grep "\"id\": ${w8},")
    o[$w9]=$(hyprctl workspaces -j | grep "\"id\": ${w9},")
    o[$w10]=$(hyprctl workspaces -j | grep "\"id\": ${w10},")

    fws=$(hyprctl activeworkspace | grep "workspace ID" | awk '{ print $3 }')

    wsbtn() {
        char=""
        if [[ $1 -eq $fws ]]; then
            f=" focused"
            char=""
        fi
        if [[ -n "${o[$1]}" ]]; then
            o=" ws_occupied"
        fi
        echo "(button :class \"ws_btn$f$o\" :halign \"center\" :valign \"center\" :onclick \"hyprctl dispatch workspace $1\" \"${char}\")"
    }

    echo "(box :spacing 5 :orientation \"h\" :halign \"center\" :valign \"center\" :vexpand true :space-evenly true $(wsbtn $w1) $(wsbtn $w2) $(wsbtn $w3) $(wsbtn $w4) $(wsbtn $w5) $(wsbtn $w6) $(wsbtn $w7) $(wsbtn $w8) $(wsbtn $w9) $(wsbtn $w10))"
}

workspaces $1
socat -U - UNIX-CONNECT:$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock | while read -r line; do
    case $line in
    workspacev2* | openwindow* | closewindow* | movewindow* | activemon* | activewindowv2* | createworkspacev2* | destroyworkspacev2* | focusedmon)
        workspaces $1
        ;;
    esac
done
