#!/usr/bin/env sh

socat -U - UNIX-CONNECT:$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock | while read -r line; do
    case $line in
    activewindowv2*)
        echo "$line"
        ;;
    esac
done
