#!/usr/bin/env sh

HYPRGAMEMODE=$(hyprctl getoption animations:enabled | awk 'NR==1{print $2}')
if [ "$HYPRGAMEMODE" = 1 ]; then
    hyprctl --batch "\
        keyword animations:enabled 0;\
        keyword decoration:drop_shadow 0;\
        keyword decoration:blur:enabled 0"
    notify-send --app-name=Hyprland \
        'Game Mode is enabed' \
        'All effects and animations have been disabled for a better video game performance.'
    exit
fi
hyprctl reload
notify-send --app-name=Hyprland \
    'Game Mode is disabled' \
    'All effects and animations have been enabled for a nicer look.'
